steps:
  # Build and push FastAPI container image
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "API",
        "-t",
        "us-central1-docker.pkg.dev/$_PROJECT_ID/$_ARTIFACT_REPO/$_IMAGE_NAME_FS:$_ENV_API_NAME"
      ]
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "us-central1-docker.pkg.dev/$_PROJECT_ID/$_ARTIFACT_REPO/$_IMAGE_NAME_FS:$_ENV_API_NAME"
      ]
  # Build and push Streamlit container image
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "API/streamlit",
        "-t",
        "us-central1-docker.pkg.dev/$_PROJECT_ID/$_ARTIFACT_REPO/$_IMAGE_NAME_ST:$_ENV_ST_NAME"
      ]
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push", # Push the Streamlit container image to Artifact Registry
        "us-central1-docker.pkg.dev/$_PROJECT_ID/$_ARTIFACT_REPO/$_IMAGE_NAME_ST:$_ENV_ST_NAME"
      ]  

  
 
options:
  logging: CLOUD_LOGGING_ONLY