steps:
  # Build and push FastAPI container image
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "API",
        "-t",
        "us-central1-docker.pkg.dev/$_PROJECT_ID/$_ARTIFACT_REPO/$_IMAGE_NAME_FS:$_ENV_API_NAME"
      ]
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "us-central1-docker.pkg.dev/$_PROJECT_ID/$_ARTIFACT_REPO/$_IMAGE_NAME_FS:$_ENV_API_NAME"
      ]

#   # Deploy FastAPI to Cloud Run and get the URL 
#   - name: "gcr.io/cloud-builders/gcloud"
#     id: "deploy-fastapi"
#     args:
#       [
#         "run",
#         "deploy",
#         "$_IMAGE_NAME_FS",
#         "--image",
#         "us-central1-docker.pkg.dev/$_PROJECT_ID/$_ARTIFACT_REPO/$_IMAGE_NAME_FS:$_ENV_API_NAME",
#         "--region",
#         "europe-north1",
#         "--platform",
#         "managed",
#         "--allow-unauthenticated",
#         "--port",
#         "8000"
#       ]
   
#   - name: "gcr.io/cloud-builders/docker"
#     args:
#       [
#         "build",
#         "API/streamlit",
#         "-t",
#         "us-central1-docker.pkg.dev/$_PROJECT_ID/$_ARTIFACT_REPO/$_IMAGE_NAME_ST:$_ENV_ST_NAME"
#       ]
#   - name: "gcr.io/cloud-builders/docker"
#     args:
#       [
#         "push", # Push the Streamlit container image to Artifact Registry
#         "us-central1-docker.pkg.dev/$_PROJECT_ID/$_ARTIFACT_REPO/$_IMAGE_NAME_ST:$_ENV_ST_NAME"
#       ]

#   #Deploy Streamlit to Cloud Run, with the FastAPI URL as an environment variable  
#   - name: "gcr.io/cloud-builders/gcloud" # Deploy Streamlit to Cloud Run, with the FastAPI URL as an environment variable
#     args:
#       [
#         "run",
#         "deploy",
#         "$_IMAGE_NAME_ST",
#         "--image",
#         "us-central1-docker.pkg.dev/$_PROJECT_ID/$_ARTIFACT_REPO/$_IMAGE_NAME_ST:$_ENV_ST_NAME",
#         "--region",
#         "europe-north1",
#         "--platform",
#         "managed",
#         "--allow-unauthenticated",
#         "--port",
#         "8501",
#         "--set-env-vars",
#         "FASTAPI_URL= https://fastapi-972701618815.europe-north1.run.app" # Set FastAPI URL as an environment variable for Streamlit as hardcoding the URL is not recommended
#       ]
 
# options:
#   logging: CLOUD_LOGGING_ONLY