version: '3.9'
services:
  spark:
    build: .
    ports:
      - "8096:19888"
    volumes:
      - /home/septim239/Spark/files:/files
      - /home/septim239/Spark/transfer:/app/transfer


  mlflow:
    build:  mlflow
    #image: bitnami/mlflow:latest
    #build:
    #    context: .
    #   dockerfile: mlflow/Dockerfile
    #command: mlflow server -h 0.0.0.0 -p 5000
    ports:
      - "5000:5000"
    volumes:
      - /home/septim239/mlruns:/app/mlruns
      - /home/septim239/mlflow:/app/mlflow
