image: google/cloud-sdk:latest

variables:
  #PROJECT_ID: your-project-id
  CLUSTER_NAME: bankprediction
  CLUSTER_ZONE: us-central1-a  # e.g., us-central1-a
  GCR_HOSTNAME: gcr.io
  KUBE_NAMESPACE: default
  ENV_API_NAME: "api-0.1"
  ENV_ST_NAME: "streamlit-0.1"
  IMAGE_NAME_FS: "fastapi"
  IMAGE_NAME_ST: "streamlit"
  ARTIFACT_REPO: "bankprediction"

steps:
  # Build and push FastAPI container image
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "API",
        "-t",
        "us-central1-docker.pkg.dev/$_PROJECT_ID/$_ARTIFACT_REPO/$_IMAGE_NAME_FS:$_ENV_API_NAME"
      ]
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "us-central1-docker.pkg.dev/$_PROJECT_ID/$_ARTIFACT_REPO/$_IMAGE_NAME_FS:$_ENV_API_NAME"
      ]

   - name: "gcr.io/cloud-builders/docker" # Build and push Streamlit container image
    args:
      [
        "build",
        "API/streamlit",
        "-t",
        "us-central1-docker.pkg.dev/$_PROJECT_ID/$_ARTIFACT_REPO/$_IMAGE_NAME_ST:$_ENV_ST_NAME"
      ]
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push", # Push the Streamlit container image to Artifact Registry
        "us-central1-docker.pkg.dev/$_PROJECT_ID/$_ARTIFACT_REPO/$_IMAGE_NAME_ST:$_ENV_ST_NAME"
      ]
