apiVersion: v1
kind: Service
metadata:
  name: fastapi-service # service name that we use in url in streamlit app
spec:
  selector:
    app: fastapi # app name that we use in deployment file
  ports: 
  - protocol: TCP # protocol
    port: 80 # port
    targetPort: 8000 # target port
  type: LoadBalancer