apiVersion: v1
kind: Service
metadata:
  name: fastapi-service # service name that we use in url in streamlit app
spec:
  selector:
    app: fastapi
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
  type: LoadBalancer